### ISSUE TITLE
Create Use Case / Misuse Case Diagram for Data Synchronization

### ISSUE THREAD

**Issue by Chunleshy** [gprasanthi9/Debug-Squad-Seafile#12]

**Comment by gprasanthi9** [comment]
![Image](https://github.com/user-attachments/assets/1a8bf3cd-e3b1-4f1d-add1-a6f554ca74a0)

**Comment by gprasanthi9** [comment]
![Image](https://github.com/user-attachments/assets/26218b04-bbd6-44ef-9697-006969a3685a)

**Comment by gprasanthi9** [comment]
Added Usecase and Misusecase of Data Synchronization
