### ISSUE TITLE
Assurance case in  data synchronization domain

### ISSUE THREAD

**Issue by Chunleshy** [gprasanthi9/Debug-Squad-Seafile#19]
Assurance case in  data synchronization domain following the instructions on canvas

**Comment by gprasanthi9** [comment]
https://github.com/gprasanthi9/Debug-Squad-Seafile/pull/25

Raised PR and send for peer review

**Comment by gprasanthi9** [comment]
Got approved from the reveiwers and moved to main branch

**Comment by gprasanthi9** [comment]
All tasks are completed
