### ISSUE TITLE
Create Use Case diagram for Login

### ISSUE THREAD

**Issue by Chunleshy** [gprasanthi9/Debug-Squad-Seafile#9]

**Comment by wein-uno** [comment]
Testing first upload
![Image](https://github.com/user-attachments/assets/75c0f73d-6a22-4d5e-baec-a90dde213e28)
![Image](https://github.com/user-attachments/assets/82d63576-af9e-49a4-80f0-f03f180f20cf)

**Comment by wein-uno** [comment]
Added files under a directory I created.
